### PR TITLE
Replace HTTP client with Axios

### PR DESCRIPTION
**Pull request by Dumeng**
Replace Angular $HTTP and jquery ajax with Axios.
The rendering issue caused by native Promise is also fixed.

### CODE REVIEW

**Comment by listen1** [comment]
It seems to work. But call applyAsync every promise seems too heavy and lose angularjs framework efficient.

So maybe we can consider better way to do that and ensure the overhead using axios is acceptable.

**Comment by Dumeng** [comment]
Or we can use AngularJS build-in Promise implement [$q](https://docs.angularjs.org/api/ng/service/$q). But its mechanism should be the same, calling _$apply_ when a Promise resolved.

**Comment by listen1** [comment]
I think $q is better, because it only updates when you specify a promising with $q, but rewrite window.Promise will  call $apply whenever promise resolved.

**Comment by listen1** [comment]
nice work to wrap axios request method. But when I test, I found netease hot playlist page keep loading, I'm not sure what is  the problem. can you test and confirm that? thanks.

**Comment by Dumeng** [comment]
The function should work properly now.

**Pull request merged**
