### PR TITLE
Migrate Providers to TS

### PR DESCRIPTION
**Pull request by Dumeng**
Migrate remained provider js files to ts

### CODE REVIEW

**Comment by Dumeng** [comment]
JS/TS doesn't have concept of pure static class. It's should be an object. Refer to [this](https://www.typescriptlang.org/docs/handbook/2/classes.html#why-no-static-classes).

I'm consider refactor all current provider classes to pure objects. And this will help to find out 'not implement' error in the compile-time or build-time instead runtime.

**Comment by Dumeng** [comment]
And also, I'm considering move the metadata of the providers i to a member of providers. This will help to reduce the complex of implementing and managing new providers. But it's totally necessary for current codebase.

**Comment by listen1** [comment]
Future work:
* 

> JS/TS doesn't have concept of pure static class. It's should be an object. Refer to [this](https://www.typescriptlang.org/docs/handbook/2/classes.html#why-no-static-classes).
> 
> I'm consider refactor all current provider classes to pure objects. And this will help to find out 'not implement' error in the compile-time or build-time instead runtime.

I think we can delete base class and only use interface, so if developer create new provider and forget to implement some method, there will be warning in compile time.

Meta info can also added as a class method such as `searchable() => Boolean`, so developers should define those methods to let complie success.

**Comment by listen1** [comment]
And btw, please run `yarn format` before commit to keep consistant format. I'll do that on next branch for now.

**Comment by Dumeng** [comment]
> And btw, please run `yarn format` before commit to keep consistant format. I'll do that on next branch for now.

Got it. The git hook may not work as expected sometimes.

**Pull request merged**
