### PR TITLE
Fix issue on Client plugins refactor merge

### PR DESCRIPTION
**Pull request by Dumeng**
Reverts listen1/listen1_chrome_extension#530

~~**IMPORTANT: NOT READY FOR MERGE**~~

### CODE REVIEW

**Comment by listen1** [comment]
Thanks for resubmit. 

The most difficult part of split library to one without angular is how to use these library in angular and let angular know varibles in these library (or we can call it state) changes. If these changes are not detected by angularjs, some weired problem happend (such as github status are not shown, playlist is not updated).

I still don't have a clear answer to this question, so I'm reading angularjs docs to find some best practise. If anyone has some clues, please comment.

**Comment by Dumeng** [comment]
The $scope of angularJS components is isolated namespace. The only way to access external variables is by creating a reference of them in the $scope.

The data binding is a similar sense. The angular only watch changes of varibles in the $scope.

**Comment by Dumeng** [comment]
Ready for Review

**Comment by listen1** [comment]
please make sure function working before reviewing, at least test related process to avoid mistake.

**Pull request merged**
