### PR TITLE
use map to map source id and source name; some clean work.

### PR DESCRIPTION
**Pull request by junhan-z**
Cool project. Hope my tiny change helps improve it.
- I think mapping could be a better way to manage the source, especially when you have more source in future, which I bet you will. Actually, if we think a step further, should we really use a number to map the source? How about 

```
var sourceMapping = {
  'Xiami': 'xiami',
  'QQ': 'qq'
  ...
};

function getSourceName(sourceName) {
  return sourceMapping[sourceName];
}
```

And call them from AngularJS with a name instead of a number?
- Helped clean some code formatting. A space after comma is recommended; always using a semicolon to end expression is recommended too in Javascript.

Besides, the naming can be improved. I saw lower_case_with_underscore and lowerCamelCase mixed. It's better to use the CamelCase as [Javascript naming](https://en.wikipedia.org/wiki/Naming_convention_%28programming%29#JavaScript) indicates.

One thing I noticed and I'm also not sure is that when I selected '虾米' as the source under "精选歌单", there is nothing, which is the case in both code before and after the change.

Maybe add some unit tests to your project?

### CODE REVIEW

**Comment by junhan-z** [comment]
This is the one I was trying to say!

**Comment by richdho** [comment]
@junhan-z , I think the Author @listen1 comes from a python background(correct me if I am wrong),  and I agree with you that it would be good if it follows best practice in JavaScript. Furthermore, many development tools can be added to this project, such as sass, npm, jslint, unit tests, live reloading. It also would be better to follow some [style guide](https://github.com/johnpapa/angular-styleguide/blob/master/a1/README.md). 
I have to say that there are a lot of things going on with JavaScript today, it is kind of too hard to catch up.

**Comment by listen1** [comment]
thanks a lot for @junhan-z 's kind and constructive advices. 
@richdho Yes, i'm from Pythoner and newbie to js(as you have seen, listen1/listen1 is first a python server project). I'm very interesting about dev tools adding in the future. I think we can open an issue for that.
And I'll spend time to have a full code style view recently, any help is welcome.

**Comment by junhan-z** [comment]
@richdho Auh, the naming is not a big issue, as long as we stick to one style instead of mixing two of them, right? The author is awesome and I believe the code will become much better in future. 

@listen1 I'm a noob to js too!

**Comment by richdho** [comment]
In fact, I was thinking about rewriting/restructuring the app, making it more developer friendly.  But as you may have guessed, this will be time-consuming. Whether doing it or not depends on how much development work to come . If there will be only small fixes and features, I think rewriting it would be going too far. Keeping it this way is just fine.

**Comment by listen1** [comment]
I think you can provide a detail list for development to do. I think feature development and restructure are both have their own priority. If developer friendly also provides efficiency for new feature releasing or fix bug, that will be high priority.

**Comment by richdho** [comment]
I will open a new issue for this. This is a cool project, just want to do it in a cool way;)

**Comment by junhan-z** [comment]
@richdho No I don't think rewriting is needed. The author and other developers can improve it gradually. I was wondering what's your opinion of adding unit tests for it, which I think can be a huge improvement as saves review time and makes the code more stable.

@listen1 Just found that you have made a few commits, nice. I'm gonna close this PR. Actually I haven't done too much change to this repo either.

**Comment by junhan-z** [comment]
Actually, I don't need to close it.. Just updated my forked repo and now you can merge my change if it passes your review.

**Comment by richdho** [comment]
@junhan-z I opened this issue #48 for more unit tests/restructuring discussion, please take a look

**Comment by listen1** [comment]
@junhan-z that would be nice!

**Comment by junhan-z** [comment]
@listen1 I see. Will do.

**Pull request closed without merging**
