### PR TITLE
fix xiami images

### PR DESCRIPTION
**Pull request by Dumeng**
Xiami Music RIP

### CODE REVIEW

**Comment by listen1** [comment]
I'm not sure whether xiami platform has shutdown, because cover images are still working as normal.

**Comment by RecluseWind** [comment]
playlist search has shutdown......

**Comment by mikelxk** [comment]
image
The click on favored playlists will change the background color of the button.
image
While clicking on other playlists don't

**Comment by listen1** [comment]
we'll deprecate xiami in another pr. thanks for submit

**Pull request closed without merging**
