### PR TITLE
Http Client Replacement

### PR DESCRIPTION
**Pull request by Dumeng**
Unify the HTTP client to axios.

### CODE REVIEW

**Comment by Dumeng** [comment]
Thanks for the merge issue fixes

**Comment by listen1** [comment]
It seems that this PR has serious problem, as UI would not refresh after axios callback runs unless $scope.apply() is called.

Any ideas?

**Comment by listen1** [comment]
https://stackoverflow.com/questions/46521516/how-to-use-the-axios-library-with-angularjs

it seems replace $http with axios is not enough for angularjs. I'll revert this PR and have further research for solution later.

**Comment by Dumeng** [comment]
Locate the issue cause is the angularJS cannot acknowledge the fulfillment status of the native Promise. I will add a temporary patch to fix this.

**Pull request merged**
