### PR TITLE
refactor: tailwind css

### PR DESCRIPTION
**Pull request by listen1**
## What is this PR about?

tailwind suggestion: https://github.com/listen1/listen1_chrome_extension/pull/681

Tailwind css is a new framework to organize css code. Before migrate to vue3, all css classes are all in one big file, which makes it hard to maintain. Another mess up is class name. Indeed, there's few reuse of css class. 

So refactor using tailwind in deed includes two tasks:
* move big css file to components
* try to use tailwind predefine css class to rewrite component

This PR uses this method to figure out whether tailwind will handle problems existed and not introduce new complex.

## How are things going?
Migrate sidebar to tailwind style, it works good, 95% classes can be replaced with predefined class. In this progress, we also need to extract some duplicate code into component. 

I refer theme switching solution by this article, which seems good. https://juejin.cn/post/6971708936734900254

## Next
I'll try to move more component to tailwind, if most of situation works good, this pr will be merged into master branch.

### CODE REVIEW

**Comment by mikelxk** [comment]
Just to point out that tailwind supports jit and arbitrary values. https://tailwindcss.com/docs/just-in-time-mode Maybe we can use that to make our style more consistent with before.

**Comment by Dumeng** [comment]
Tailwind just released [the next major version](https://tailwindcss.com/blog/tailwindcss-v3#just-in-time-all-the-time). May need to upgrade the code in current PR.

**Comment by listen1** [comment]
> Tailwind just released [the next major version](https://tailwindcss.com/blog/tailwindcss-v3#just-in-time-all-the-time). May need to upgrade the code in current PR.

good idea, already upgrade to tailwind v3, build speed has been improved.

**Comment by listen1** [comment]
> Just to point out that tailwind supports jit and arbitrary values. https://tailwindcss.com/docs/just-in-time-mode Maybe we can use that to make our style more consistent with before.

nice suggestion. Arbitrary value support is what i'm looking for. Thanks.

**Comment by mikelxk** [comment]
It seems that this pr only have very little problem now like leading is quite small in setting page. I've changed its line height to 1.5 but it doesn't seem to apply to checkbox and buttons. and animation is gone when toggle playbar popup.

**Comment by listen1** [comment]
> It seems that this pr only have very little problem now like leading is quite small in setting page. I've changed its line height to 1.5 but it doesn't seem to apply to checkbox and buttons. and animation is gone when toggle playbar popup. Update: After reorder the selected song will appear above the now playing page.

1.5rem line height dose apply to checkbox but still small, i've changed to 2rem (leading-8)

**Comment by listen1** [comment]
> It seems that this pr only have very little problem now like leading is quite small in setting page. I've changed its line height to 1.5 but it doesn't seem to apply to checkbox and buttons. and animation is gone when toggle playbar popup. Update: After reorder the selected song will appear above the now playing page.

reorder song makes song appear above bug has been fixed. thanks for submit bug report

**Comment by Dumeng** [comment]
This PR is really impressive.

**Pull request merged**
