### PR TITLE
fix: lyric setting not saved

### PR DESCRIPTION
**Pull request by mikelxk**
style: make heart more consistent
🆙  deps

### CODE REVIEW

**Comment by listen1** [comment]
could you post a copy of prettier config? I found pr ususally include reformat.

**Comment by mikelxk** [comment]
That's because I‘m used to use ctrl+alt+f. The format uses the prettier config in the repo which somehow conflicts with the format eslint generates. I've add a prettier config to eslint and a pre commit hook so that every code is formatted when pushed.

**Comment by mikelxk** [comment]
update:
It seems that the config I use for .vue files are actually volar included formatter which also reads .prettierrc but acts a little bit differently. oops!

**Comment by listen1** [comment]
> update: It seems that the config I use for .vue files are actually volar included formatter which also reads .prettierrc but acts a little bit differently. oops!

that's right, let's do some research and figure out how to make it consistent. 

Check script in github action will be added in the frture, so I think it's better to config volar to follow prettier config instead to    use its own config which is hard to run check in github action env.

**Pull request merged**
