### PR TITLE
feat: add seekto actionHandler

### PR DESCRIPTION
**Pull request by mikelxk**
https://web.dev/media-session/
image

@listen1 can you help me test the seek to effect is working or not on macOS?

### CODE REVIEW

**Comment by listen1** [comment]
tested on mac successful, but some problem found.

1. 点击上一首下一首后，整个界面就消失了，在托盘区找不到了。这个应该不是这次提交导致的，可能是之前的bug
2. 拖动后可以往前或者往后一段，但是到达的不是拖动的位置。

还需要在看一下原因。不知道这个功能是否在其他平台可用，并有同样问题

**Comment by mikelxk** [comment]
Will problem 1 occur in previous commit?
Maybe we should call setPositionState after toggle prev/next.

**Comment by listen1** [comment]
entry disappears after click prev/next button is solved. Nice.

set play position is not working as expect still exists.

**Comment by mikelxk** [comment]
I've add a new func on Player called seekTime to seek in seconds.
Then seek in seconds through that function instead of seek directly in Howler.
If it the position is not working correctly. Consider adding a breakpoint or console.log after line 611 and see if seekTime given is correct?

**Comment by listen1** [comment]
ok. seems problem still exists. I'll debug it and find out reason

**Pull request merged**
